export const REQUEST_KEYS = 'REQUEST_KEYS';
export const RECEIVE_KEYS = 'RECEIVE_KEYS';
export const REQUEST_NAMESPACES = 'REQUEST_NAMESPACES';
export const RECEIVE_NAMESPACES = 'RECEIVE_NAMESPACES';
