export const REQUEST_KEYS = 'REQUEST_KEYS_ANALYSIS';
export const RECEIVE_KEYS = 'RECEIVE_KEYS_ANALYSIS';
export const REQUEST_NAMESPACES = 'REQUEST_NAMESPACES_ANALYSIS';
export const RECEIVE_NAMESPACES = 'RECEIVE_NAMESPACES_ANALYSIS';
