export const SEND_KEYVALUE_PAIR = 'SEND_KEYVALUE_PAIR';
export const GET_METADATA = 'GET_METADATA';
export const UPDATE_KEY = 'UPDATE_KEY';
export const REQUEST_KEYS = 'REQUEST_KEYS';
export const RECEIVE_KEYS = 'RECEIVE_KEYS';
export const REQUEST_VALUE = 'REQUEST_VALUE';
export const RECEIVE_VALUE = 'RECEIVE_VALUE';
export const TOGGLE_ADD = 'TOGGLE_ADD';
